#define VERSION_MAJOR     5
#define VERSION_MINOR     0
#define VERSION_QFE       26 
#define VERSION_BUILD     244

#define VERSION_BUILD_DATE    "05/11/2024"
#define VERSION_BUILD_TIME    "11:15:08UTC"
#ifndef VER_H
#define VER_H
#define		_STR(x) #x
#define		STR(x) _STR(x)
#define		VERSION_NUMBER			VERSION_MAJOR,VERSION_MINOR,VERSION_QFE,VERSION_BUILD
#define		VERSION_STRING			STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_QFE) "-" STR(VERSION_BUILD)
#define		VERSION_COMPANY			""
#define		VERSION_COPYRIGHT		"(c) " + VERSION_BUILD_DATE + " FAST GmbH"
#define		VERSION_TRADEMARK		""
#define		VERSION_BUILD_DATE_TIME	VERSION_BUILD_DATE " - " VERSION_BUILD_TIME
#define     VERSION_NUMBER_U64  ((VERSION_MAJOR << 32UL) + (VERSION_MINOR << 24UL) + (VERSION_QFE << 16UL) + (VERSION_BUILD & 0xFFFF))
#endif